# Generated by Django 5.2.3 on 2025-06-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
